version     = "0.0.1"
name        = "bio_seq"
author      = "Kerry A. Cobb"
description = "A Nim library for biological sequence data."
license     = "MIT"
srcDir      = "src"
requires "nim >= 1.2.0"
