

# type
#   Sequence = ref object
#     length: int
#     array: seq[uint8] 

# var 
#   s = "ATGCATGCAT"
#   bytes = (s.len + sizeof(uint) - 1) div sizeof(uint) 
#   a = newSeq[uint8](bytes)

import bitvector

var 
  s = "ATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGC"
  b = newBitVector[uint](s.len*2)
echo s.len
echo s.len*2
echo b
