name: BioSeq Docs CI 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: nimlang/nim
    steps:
      - uses: actions/checkout@v3
      - name: build-html
        run: nim doc --project --index:on --git.url:https://github.com/kerrycobb/BioSeq --outdir:htmldocs src/bioseq.nim
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./htmldocs

      #   run: nim doc --project --index:on --git.url:https://github.com/kerrycobb/BioSeq --outdir:htmldocs src/bioseq.nim
      #   with:
      #     branch: gh-pages
      #     folder: .


# # Simple workflow for deploying static content to GitHub Pages
# name: Bioseq Docs CI

# on:
#   push:
#   pull_request:

# jobs:


#   before:
#     runs-on: ubuntu-latest
#     if: "! contains(github.event.head_commit.message, '[skip ci]')"
#     steps:
#       - run: echo "not contains '[skip ci]'"

#   test:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os:
#           - ubuntu-latest
#             #- windows-latest
#             #- macOS-latest
#         nim-version:
#           - '1.4.0'
#           - 'stable'
#     needs: before
#     steps:
#       - uses: actions/checkout@v1
#       - name: Cache nimble
#         id: cache-nimble
#         uses: actions/cache@v1
#         with:
#           path: ~/.nimble
#           key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
#       - uses: jiro4989/setup-nim-action@v1
#         with:
#           nim-version: ${{ matrix.nim-version }}

#       # see. https://github.com/actions/virtual-environments/issues/675
#       - name: Fix apt packages
#         run: |
#           sudo sed -i 's/azure\.//' /etc/apt/sources.list
#           sudo apt update -yqq
#       # - run: nimble install -Y
#       - uses: actions/checkout@v2.3.1
#       - run: nim doc --project --index:on --git.url:https://github.com/kerrycobb/bioseq --outdir:src/htmldocs src/anonimongo.nim
#       - name: Deploy docs
#         uses: JamesIves/github-pages-deploy-action@4.1.4
#         with:
#           branch: gh-pages
#           folder: .





      # - uses: kerrycobb/github-pages-deploy-action@4.1.4
      # - name: Build docs
      #   run: nim doc --project --index:on --git.url:https://github.com/kerrycobb/BioSeq --outdir:src/htmldocs src/bioseq.nim
      #   with:
      #     branch: gh-pages
      #     folder: .






# name: Deploy to GitHub pages
# on:
#   push:
#     branches: [ main ]
# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2

#     - name: Generate static VuePress files
#       uses: actions/setup-node@v2
#       with:
#         node-version: '16'
#     - run: npm ci
#     - run: npm run build

#     - name: Init new repo in dist folder and commit generated files
#       run: |
#         cd docs/.vuepress/dist
#         git init
#         git add -A
#         git config --local user.email "action@github.com"
#         git config --local user.name "GitHub Action"
#         git commit -m 'deploy'

#     - name: Force push to destination branch
#       uses: ad-m/github-push-action@v0.5.0
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         branch: gh-pages
#         force: true
#         directory: ./docs/.vuepress/dist