name: BioSeq CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: nimlang/nim
    steps:
      - uses: actions/checkout@v3
      - name: Run tests 
        run: nimble -y test 
      
      - name: Build docs
        run: nim doc --project --index:on --git.url:https://github.com/kerrycobb/BioSeq --outdir:src/htmldocs src/bioseq.nim
        uses: kerrycobb/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .
